In [10]:
import torch
from torch import Tensor
from torch.utils.data import dataset
from torchtext import datasets
from grok.transformer import Transformer

from torchtext.datasets import PennTreebank
from torchtext.vocab import build_vocab_from_iterator
from torchtext.data.utils import get_tokenizer

from typing import Tuple, Dict
import math

In [11]:
train_iter = datasets.PennTreebank(root="../data", split="train")
tokenizer = get_tokenizer('basic_english')
vocab = build_vocab_from_iterator(map(tokenizer, train_iter), specials=['<unk>'])
vocab.set_default_index(vocab['<unk>'])

def data_process(raw_text_iter: dataset.IterableDataset) -> torch.Tensor:
    """Converts raw text into a flat Tensor."""
    data = [torch.tensor(vocab(tokenizer(item)), dtype=torch.long) for item in raw_text_iter]
    return torch.cat(tuple(filter(lambda t: t.numel() > 0, data)))


In [12]:
train_data = data_process(train_iter)
train_data.train = True
train_data.shape

torch.Size([924412])

In [13]:
def data_process(raw_text_iter: dataset.IterableDataset) -> torch.Tensor:
    """Converts raw text into a flat Tensor."""
    data = [torch.tensor(vocab(tokenizer(item)), dtype=torch.long) for item in raw_text_iter]
    return torch.cat(tuple(filter(lambda t: t.numel() > 0, data)))


def get_ptb_dataset(train_pct: float, split:str = "train", data_dir:str ="../data"):
        data_iter = datasets.PennTreebank(root=data_dir, split=split)
        tokenizer = get_tokenizer('basic_english')
        
        if split != "train":
            train_iter = datasets.PennTreebank(root=data_dir, split="train")
            vocab = build_vocab_from_iterator(map(tokenizer, train_iter), specials=['<unk>'])
        else:
            vocab = build_vocab_from_iterator(map(tokenizer, data_iter), specials=['<unk>'])
        
        vocab.set_default_index(vocab['<unk>'])
        
        data = data_process(data_iter)
        data = data[:int(train_pct*len(data))]
        if split =="train":
            data.train = True
        data.tokenizer = tokenizer
        data.vocab = vocab
        return data


        

In [14]:
def batchify(data: torch.Tensor, bsz: int) -> Tensor:
    """Divides the data into bsz separate sequences, removing extra elements
    that wouldn't cleanly fit.

    Args:
        data: Tensor, shape [N]
        bsz: int, batch size

    Returns:
        Tensor of shape [N // bsz, bsz]
    """
    seq_len = data.size(0) // bsz
    data = data[:seq_len * bsz]
    data = data.view(bsz, seq_len).contiguous()
    return data

bptt = 5
def get_batch(source: torch.Tensor, i: int) -> Tuple[Tensor, Tensor]:
    """
    Args:
        source: Tensor, shape [full_seq_len, batch_size]
        i: int

    Returns:
        tuple (data, target), where data has shape [seq_len, batch_size] and
        target has shape [seq_len * batch_size]
    """
    print(source.shape)
    seq_len = min(bptt, source.size(1) - 1 - i)
    data = source[:,i:i+seq_len]
    target = source[:,i+1:i+1+seq_len]
    return data, target


class PTBIterator(torch.utils.data.IterableDataset):
    """
    An iterator over batches of data in an ArithmeticDataset
    """

    def __init__(
        self,
        dataset: torch.utils.data.Dataset,
        device: torch.device,
        batchsize: float = 2,
        shuffle: bool = True,
    ) -> None:
        """
        :param dataset: the dataset to iterate over
        :param device: the torch device to send batches to
        :param batchsize_hint: * 0 means we use a default batchsize
                               * -1 means the entire dataset
                               * float between 0 and 1 means each batch is
                                 that fraction of the DS
                               * int > 1 means that specific batch size
        :param shuffle: whether or not to randomly shuffle the dataset
        """
        self.dataset = dataset
        self.data = batchify(self.dataset, batchsize)
        self.device = device
        self.reset_iteration(shuffle=shuffle)
        self.batchsize = batchsize

    def reset_iteration(self, shuffle=True):
        self.index = 0
        if shuffle and self.dataset.train:
            self.permutation = torch.randperm(len(self.dataset))
        else:
            self.permutation = torch.arange(len(self.dataset))

    
    def __iter__(self):
        """
        :returns: this iterator
        """
        return self

    def __next__(self) -> Dict[str, Tensor]:
        """
        Returns one batch of data.

        :raises: StopIteration when we're out of data
        :returns: batch tensor of shape (self.batchsize, tokens_per_eq)
        """
        self.index += 1
        return get_batch(self.data, self.index)
        
        
    def __len__(self) -> int:
        """
        :returns: the total number of batches
        """
        return math.ceil(len(self.dataset) / self.batchsize)

    

In [133]:
train_iter = PTBIterator(get_ptb_dataset(0.2), torch.device("cpu"))

In [134]:
len(train_iter)

92441

In [135]:
data,target = next(iter(train_iter))
data, target

torch.Size([2, 92441])


(tensor([[9893, 9894, 9896, 9897, 9898],
         [   0, 1192,    2,    2,    3]]),
 tensor([[9894, 9896, 9897, 9898, 9902],
         [1192,    2,    2,    3,    1]]))

## Test grok internals

In [7]:
from grok.training_ptb import TrainableTransformer
from grok  import training_ptb
import os
import argparse

In [8]:
hparams = argparse.Namespace(random_seed=-1, gpu=0, max_epochs=None, max_steps=1000000, log=False, load_path=None, resume=False, run_path=None, batchsize=512, optimizer='Adam', n_layers=2, n_heads=4, d_model=128, dropout=0.0, weight_noise=0.0, non_linearity='relu', max_context_len=50, dataset='ptb', math_operator='+', operand_length=None, train_data_pct=0.5, warmup_steps=10, anneal_lr_steps=100000, anneal_lr=False, max_lr=0.001, weight_decay=0, weight_decay_kind='to_zero', noise_factor=0, save_activations=False, save_outputs=False, logdir='/home/alpha91/data/codes/grok/nbs/logs', datadir='/home/alpha91/data/codes/grok/nbs/data')




In [9]:
model = TrainableTransformer(hparams).float()

Namespace(random_seed=-1, gpu=0, max_epochs=None, max_steps=1000000, log=False, load_path=None, resume=False, run_path=None, batchsize=512, optimizer='Adam', n_layers=2, n_heads=4, d_model=128, dropout=0.0, weight_noise=0.0, non_linearity='relu', max_context_len=50, dataset='ptb', math_operator='+', operand_length=None, train_data_pct=0.5, warmup_steps=10, anneal_lr_steps=100000, anneal_lr=False, max_lr=0.001, weight_decay=0, weight_decay_kind='to_zero', noise_factor=0, save_activations=False, save_outputs=False, logdir='/home/alpha91/data/codes/grok/nbs/logs', datadir='/home/alpha91/data/codes/grok/nbs/data')


In [10]:
model.val_dataset.shape[0] // 7

10477

In [11]:
train_iter = model.val_dataloader()

In [12]:
batch = next(iter(train_iter))

batch["text"].shape, batch["target"].shape

(torch.Size([10477, 5]), torch.Size([10477, 5]))

In [6]:
model._step(batch, 0)


Y => torch.Size([512, 5]) ('N', 'Seq', 'Vocab_size')
Y_hat =>  torch.Size([512, 5, 9922]) ('N', 'Seq', 'Vocab_size')
Acc y shapes torch.Size([512, 5]) torch.Size([512, 5])


(tensor(9.3999, grad_fn=<NllLoss2DBackward0>),
 tensor(0.),
 0.0011077311847963894,
 tensor([[9893, 9894, 9896, 9897, 9898],
         [ 698,    5,  241,  376,   12],
         [8678,    6, 1742,  566,  128],
         ...,
         [   5, 4626,  308,  460, 2906],
         [ 232,   72,    3,    1,    0],
         [   5, 3279, 5517, 1273,    7]]),
 tensor([[[ 0.7249, -0.5114,  0.2801, -0.6231, -0.0155],
          [ 0.7394, -0.1450, -0.0189, -0.2631,  0.1150],
          [ 0.4053,  0.1275,  0.2674, -0.0627,  0.6148],
          ...,
          [-0.2284,  0.5369,  0.9074,  0.5625,  0.6269],
          [-0.0510,  0.1802, -0.2740, -0.0541, -0.9548],
          [ 1.1685,  1.1097,  1.0924,  0.2148,  0.7769]],
 
         [[ 0.3628,  0.0516, -0.2601, -0.3385,  0.1052],
          [-0.1659, -0.0472, -0.3190, -0.0921,  0.1380],
          [ 0.4108,  0.5734,  0.9389,  0.3070, -0.6408],
          ...,
          [-0.1876, -0.0895, -0.0840, -0.7930, -0.3165],
          [-0.2218,  0.5158,  0.1771, -0.6025, -0.6